### ISSUE TITLE
文章页面里也贯彻一下主题背景吧~

### ISSUE THREAD

**Issue by mrj1018** [teamhola/holakit#2]
如题，似乎现在主页挺漂亮的，但是文章页面里好像有点黯然失色的感觉？
希望能把主题颜色、主题背景图片应用到文章页面里去，这样整个博客更显得浑然一体，主题感更强。
感谢！

**Comment by laosb** [comment]
您好，本代码仓库为 HolaKit 开源 CSS 组件库，并非洛谷博客 holakit 主题的代码仓库，尽管后者使用了前者。您所反馈的内容并非 HolaKit 组件库本身，建议您前往[洛谷博客前端代码仓库](https://github.com/luogu-dev/luogu-blog-frontend)反馈。谢谢您的反馈，本 issue 因与本仓库无关而 close。
